# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [11]:
arr = np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [12]:
arr=np.array([1]*10)

#### Create an array of 10 fives

In [4]:
arr=np.array([5]*10)


#### Create an array of the integers from 10 to 50

In [6]:
arr=np.array([list(range(10,51))])


#### Create an array of all the even integers from 10 to 50

In [8]:
arr=np.array([list(range(10,51,2))])


#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr=(np.arange(9)).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [19]:
arr=np.identity(3)


#### Use NumPy to generate a random number between 0 and 1

In [20]:
from numpy import random
arr=random.rand()


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [16]:
from numpy import random
arr=random.normal(0,1,25)
arr

array([-1.20328511,  0.24615778, -0.54428102, -0.60534616, -1.46874635,
        0.60731453,  1.08433543, -0.842758  ,  0.38238288,  0.16531261,
        0.07403422, -1.02209496, -0.21699431,  0.19910139,  0.19277281,
        1.34080541, -0.10600271,  1.25169679,  0.46326342,  2.31687013,
        1.14144141,  0.10201743, -0.52266774, -0.37216551, -0.85106569])

#### Create the following matrix:

In [23]:
arr=np.arange(0.01,1.01,0.01).reshape(10,10)



#### Create an array of 20 linearly spaced points between 0 and 1:

In [26]:
arr=np.linspace(0,1,20)


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [40]:
arr1=np.array([list(range(1,26))]).reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [41]:
arr2=np.array([list(range(12,27))]).reshape(3,5)[:, :4]
print(arr2)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [42]:
print(arr1[3,4])

20


In [45]:
print(arr1[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [46]:
print(arr2[2,:])

[22 23 24 25]


In [50]:
print(arr1[3:5 , :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!